name: CD Deploy

on:
  registry_package:
    types: [published]

jobs:
  deploy:
    uses: AgentGG00/workflows/.github/workflows/cd-deploy.yml@main
    with:
      project_name: "server-dashboard"
      bootstrap: true
    secrets:
      host: ${{ secrets.DASHBOARD_HOST }}
      user: ${{ secrets.DASHBOARD_USER }}
      ssh_key: ${{ secrets.DASHBOARD_SSH_KEY }}
      env_content: ${{ secrets.DASHBOARD_ENV }}