name: Publish
on:
  push:
    tags:
      - 'v*'
permissions:
  packages: write
  contents: read
jobs:
  publish:
    uses: AgentGG00/workflows/.github/workflows/publish.yml@main
    secrets: inherit
