name: Publish

on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: AgentGG00/workflows/.github/workflows/publish.yml@main
    secrets: inherit