name: Review

on:
  pull_request:
    branches:
      - main

jobs:
  review:
    uses: AgentGG00/workflows/.github/workflows/review.yml@main
    secrets: inherit
    permissions:
      pull-requests: write
